### ISSUE TITLE
Error: Require Graphviz 2.38 or later

### ISSUE THREAD

**Issue by mauricioob** [bakunin95/wavi#10]
I'm getting this error on OSX, I have graphicviz installed:
$ dot -V
dot - graphviz version 2.38.0 (20140413.2041)

The output/error after I execute the command (wavi --svg reports/ out.svg) is:

finished HTML analysis...
finished js analysis...
finished misc analysis...
generating graph (could take several minutes)...
###### 

Error: Require Graphviz 2.38 or later
Graphviz is not installed, too old or the os environment path is not set proprely
Graphviz download:  http://www.graphviz.org/Download.php
Add Graphviz bin folder to environment variable path (ex.: 'C:Program Files (x86)Graphviz2.3in')
###### 
###### 

node.js:510
    function nextTick(callback) {
                     ^

RangeError: Maximum call stack size exceeded
    at process.nextTick (node.js:510:22)
    at onwrite (_stream_writable.js:335:15)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at WriteStream.Socket._writeGeneric (net.js:684:5)
    at WriteStream.Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at WriteStream.Writable.write (_stream_writable.js:207:11)
    at WriteStream.Socket.write (net.js:618:40)
    at Console.log (console.js:36:16)

any help is highly appreciated!

**Comment by adamvresky** [comment]
Same for me

**Comment by bakunin95** [comment]
Hi, i don't have an OSX to replicate the problem but considering the error message, i think i can fix it for the next version.

Thanks

**Comment by bakunin95** [comment]
Ok, its fixed in the latest version.

I found out that the problem is that mac and linux version of graphviz (from package managers)  often doesn't include libraries such as GTS (triangulation) wich means the algorithm doesn't know how to deal with overlaping nodes in the graph. I changed the graph setting so that, at least there is an output but the real solution is this:

gts has to be installed before graphivz
so enter 'sudo brew remove graphviz' to remove graphivz

and 'sudo brew install gts' and 'sudo install graphviz' to install graphviz with gts.
or
sudo port install graphviz

source (http://www.graphviz.org/Download_macos.php)
