### ISSUE TITLE
some problem when trying to use wavi

### ISSUE THREAD

**Issue by Patrik-Glendell** [bakunin95/wavi#16]
> finished HTML analysis...
> 10% JavaScripts files analyzed...
> 14% JavaScripts files analyzed...
> 19% JavaScripts files analyzed...
> 24% JavaScripts files analyzed...
> 29% JavaScripts files analyzed...
> 33% JavaScripts files analyzed...
> 38% JavaScripts files analyzed...
> 43% JavaScripts files analyzed...
> 48% JavaScripts files analyzed...
> 52% JavaScripts files analyzed...
> 57% JavaScripts files analyzed...
> 62% JavaScripts files analyzed...
> 67% JavaScripts files analyzed...
> 71% JavaScripts files analyzed...
> 76% JavaScripts files analyzed...
> 81% JavaScripts files analyzed...
> C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\sqlite3\lib\trace.js:28
>                     throw err;
>                     ^
> 
> TypeError: Cannot read property 'constructor' of undefined
>     at C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb-sqlite3\lib\sqlite3.js:323:34
>     at Array.forEach (native)
>     at buildWhere (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb-sqlite3\lib\sqlite3.js:312:
>     at SQLite3.all (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb-sqlite3\lib\sqlite3.js:281
>     at Function.all (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb\lib\model.js:489:25)
>     at Function.findOne (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb\lib\model.js:624:10)
>     at C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\lib\extractor\lib\deps\database.js:281:9
>     at C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb\lib\model.js:626:9
>     at C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb\lib\model.js:526:13
>     at SQLite3.<anonymous> (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb-sqlite3\lib\sqlite
> --> in Database#all('SELECT \* FROM `Node` WHERE `rootParentId` = ? AND `rawName` = ? LIMIT 1', [ 24, 'NodeHeader' ], [Function])
>     at SQLite3.query (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb-sqlite3\lib\sqlite3.js:6
>     at SQLite3.queryAll (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb-sqlite3\lib\sqlite3.j
>     at SQLite3.all (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb-sqlite3\lib\sqlite3.js:294
>     at Function.all (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb\lib\model.js:489:25)
>     at Function.findOne (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\node_modules\jugglingdb\lib\model.js:624:10)
>     at Object.module.exports.addExtend (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\lib\extractor\lib\deps\databas
>     at Object.module.exports.addExtend (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\lib\extractor\lib\parsers\pars
> 14)
>     at Array.module.exports.after (C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\lib\extractor\lib\parsers\javascrip
> 
> ```
> at C:\Users\PatrikGlendell\AppData\Roaming\npm\node_modules\wavi\lib\extractor\lib\deps\languages\jsClass.js:320:41
> ```

**Comment by Patrik-Glendell** [comment]
After changing the jugglingdb verison to '1.0.X' and the jugglingdb-sqlite3 to 'latest' it works fine
