### ISSUE TITLE
Not able to execute the tool

### ISSUE THREAD

**Issue by prmondal** [bakunin95/wavi#17]
WARNING: JugglingDB adapter "sqlite3" is not installed,
so your models would not work, to fix run:

```
npm install jugglingdb-sqlite3 
```

/usr/local/lib/node_modules/wavi/node_modules/jugglingdb/lib/schema.js:250
    this.adapter.define({
                ^

TypeError: Cannot read property 'define' of undefined
    at Schema.defineClass [as define](/usr/local/lib/node_modules/wavi/node_modules/jugglingdb/lib/schema.js:250:17)
    at module.exports (/usr/local/lib/node_modules/wavi/lib/extractor/lib/models/link.js:2:26)
    at Object.module.exports.startServer (/usr/local/lib/node_modules/wavi/lib/extractor/lib/deps/database.js:31:11)
    at /usr/local/lib/node_modules/wavi/lib/extractor/lib/deps/extractor.js:16:11
    at fn (/usr/local/lib/node_modules/wavi/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/wavi/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/wavi/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/wavi/node_modules/async/lib/async.js:706:43
    at /usr/local/lib/node_modules/wavi/node_modules/async/lib/async.js:167:37
    at Object.async.waterfall (/usr/local/lib/node_modules/wavi/node_modules/async/lib/async.js:710:44)

I have installed "jugglingdb-sqlite3" by executing "npm install jugglingdb-sqlite3" already.

**Comment by jitcoder** [comment]
+1
