### ISSUE TITLE
`wavi` command not executing

### ISSUE THREAD

**Issue by xbreid** [bakunin95/wavi#23]
Hello, I have came across this, and looks great for what I need. I tried to install wavi to my package and when trying to run wavi the command is not found.

Does this happen for anyone else? Has this become obsolete?

**Comment by bakunin95** [comment]
Are you running in Ubuntu ? If wavi is not found you can give the absolute path to it, npm would install it somewhere in /usr/local/bin/

Can you try this:

nodejs /usr/local/bin/wavi /path/to/website graph.svg

and make sure to edit "path/to/website" to the real website path.

**Comment by xbreid** [comment]
I am running on MacOS, I was able to get wavi to run by executing this command:

`node /usr/local/bin/wavi /path/to/website graph.svg`

and output was this error: 

`finished analyzing, now generating graph
7
7
abort(7) at Error
    at Error (native)
    at Ga (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:49:124)
    at Fa (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:49:22)
    at v (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1172:101)
    at Array.M5 (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1157:32623)
    at zD (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1145:124892)
    at fD (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1145:110783)
    at zE (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1145:155679)
    at AE (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1145:159595)
    at BE (/usr/local/lib/node_modules/wavi/es5/lib/viz.js:1145:159770)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
Graph generated: /Users/Bar/graph.svg
Execution time: 13.784`

When I checked the graph.svg it was undefined

Essentially this is the same error that issue #21 was having.

**Comment by xbreid** [comment]
Okay, so I realized what I am doing wrong... I was trying to do the filepath to the entire project folder. I didn't realize you had to specify the filepath of the website to the folder that holds index.js/index.html. In my case this was the `/src` folder.
