### ISSUE TITLE
looks cool but does not work 

### ISSUE THREAD

**Issue by patakye** [bakunin95/wavi#8]
<pre>
WARNING: JugglingDB adapter "sqlite3" is not installed,
so your models would not work, to fix run:

    npm install jugglingdb-sqlite3 

/usr/local/lib/node_modules/wavi/node_modules/jugglingdb/lib/schema.js:250
    this.adapter.define({
                ^

TypeError: Cannot read property 'define' of undefined
    at Schema.defineClass [as define] (/usr/local/lib/node_modules/wavi/node_modules/jugglingdb/lib/schema.js:250:17)
    at module.exports (/usr/local/lib/node_modules/wavi/node_modules/relex/lib/models/link.js:2:26)
    at Object.module.exports.startServer (/usr/local/lib/node_modules/wavi/node_modules/relex/lib/deps/database.js:36:11)
    at /usr/local/lib/node_modules/wavi/node_modules/relex/lib/deps/relationsClass.js:121:12
    at fn (/usr/local/lib/node_modules/wavi/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (/usr/local/lib/node_modules/wavi/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
</pre>

any ideas?

**Comment by patakye** [comment]
i have already done the npm install jugglingdb-sqlite3 but it does not help

**Comment by bakunin95** [comment]
Never seen this error before, but in this case, jugglingdb is not installed correctly.

**Comment by imfly** [comment]
@patakye you can try to reinstall `wavi` by the follow way:

```
$ npm —registry <registry_URL> install -g wavi
```

The `registry_URL` is 

> http://registry.npmjs.org.au (Australia)
> https://registry.nodejitsu.com (US East)
> http://registry.cnpmjs.org (China)

If the installation fails, you can repeat it several times. It's because `*sqlite3` needs `node-gyp` to recompile it, but some source code is not downloaded.

**Comment by Jafnhor** [comment]
Hi, i have the exact same problem. The solution of lmfly work ? There is another solution ?
Thanks.

**Comment by vasindaniil** [comment]
> $ npm —registry <registry_URL> install -g wavi

npm tells me that this is invalid, and that there is no --registry option.

I have the same issue, and there doesn't seem to be any way to fix this on linux, this issue should definitely be reopened

**Comment by vasindaniil** [comment]
Found the issue on my part, sorry to trouble you

**Comment by elitan** [comment]
So what was the issue? Could be interesting for people trying to solve the same problem.

**Comment by bakunin95** [comment]
the issue is with jugglingdb-sqlite3 not installing. when ill have time ill look if i can revert to an older version of this package, maybe it will correct the situation.

**Comment by vasindaniil** [comment]
For me personally the issue was an improper installation of npm in general, so make sure you have a correct configuration there as well

**Comment by lucbelliveau** [comment]
The solution is to not install wavi globally; there are dependencies that won't get installed correctly (sqlite3).  Install it inside your package instead.  Or you could try using the `--unsafe-perm` parameter to npm install.
